vich_uploader:
    db_driver: orm

    mappings:
        files:
            uri_prefix: /upload/files
            upload_destination: '%kernel.project_dir%/public/upload/files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
