#!/bin/sh
npm run build
ssh t67tz_phpstorm_macos@t67tz.ftp.infomaniak.com 'cd ~/sites/project-manager.mycpnv.app/public && rm -rf build'
rsync -av ./ t67tz_phpstorm_macos@t67tz.ftp.infomaniak.com:~/sites/project-manager.mycpnv.app --include=public/build --include=vendor --exclude-from=.gitignore --exclude=".*" --exclude=deploy --exclude=assets
ssh t67tz_phpstorm_macos@t67tz.ftp.infomaniak.com 'cd ~/sites/project-manager.mycpnv.app && php-8.1 bin/console cache:clear'